import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/lib/QueryProvider";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "lebonlieu",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        <QueryProvider>
          <div className="container flex flex-col items-center w-full max-w-[1480] border my-0 mx-auto">
            <Header />
            <main className="flex flex-col items-center w-full">
              {children}
            </main>
            <Footer />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
